spring.application.name=travel-booking-system
spring.datasource.url = jdbc:postgresql://localhost:5432/travel_booking
spring.datasource.username = postgres
spring.datasource.password = ${DB_PASSWORD}
spring.datasource.driver-class-name = org.postgresql.Driver
server.error.include-message=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect